# App Infrastructure
# Provider and backend are generated by Terragrunt

module "app_stack" {
  source = "../modules/app_stack"

  project_name      = var.project_name
  environment       = var.environment
  sns_subscriptions = var.sns_subscriptions
  common_tags       = var.common_tags
}
