# CI/CD Infrastructure — Jenkins on ECS
# Provider and backend are generated by Terragrunt

module "jenkins_platform" {
  source = "../modules/jenkins-platform"

  project_name           = var.project_name
  environment            = var.environment
  vpc_cidr               = var.vpc_cidr
  public_subnet_cidrs    = var.public_subnet_cidrs
  private_subnet_cidrs   = var.private_subnet_cidrs
  master_cpu             = var.master_cpu
  master_memory          = var.master_memory
  master_image           = var.master_image
  agent_cpu              = var.agent_cpu
  agent_memory           = var.agent_memory
  agent_image            = var.agent_image
  log_retention_days     = var.log_retention_days
  jenkins_admin_user     = var.jenkins_admin_user
  jenkins_admin_password = var.jenkins_admin_password
  common_tags            = var.common_tags
}
